version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    ignore:
      - dependency-name: "astro"
        versions: ["^7.0.0"]
      - dependency-name: "@astrojs/node"
      versions: ["^11.0.0"]
