version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    ignore:
      - dependency-name: 'astro'
        versions: ['>= 6.0.0']
      - dependency-name: '@astrojs/*'
        versions: ['>= 6.0.0']
